function getData_RecordsList()
{
	arrRecordsList = new Array();
	return arrRecordsList = [

	,"Most Wins"
	,"-- Most Wins - Single Season"
	,""
	,"Most Runner-Ups"
	,"-- Most Runner-Ups - Single Season"
	,"-- Most Runner-Ups - Single Season - No Wins"
	,"-- Most Runner-Ups - No Wins in Range"
	,"-- Most Runner-Ups - No Wins in Career"
	,""
	,"Most Top 5s"
	,"-- Most Top 5s - Single Season"
	,"-- Most Top 5s - Single Season - No Wins"
	,"-- Most Top 5s - No Wins in Range"
	,"-- Most Top 5s - No Wins in Career"
	,""
	,"Most Top 10s"
	,"-- Most Top 10s - Single Season"
	,"-- Most Top 10s - Single Season - No Wins"
	,"-- Most Top 10s - No Wins in Range"
	,"-- Most Top 10s - No Wins in Career"
	,""
	,"Highest Earnings"
	,"-- Highest Earnings - Single Season"
	,"-- Highest Earnings - Single Season - No Wins"
	,"-- Highest Earnings - No Wins in Range"
	,"-- Highest Earnings - No Wins in Career"
	,""
	,"Lowest Round (Gross)"
	,"-- Lowest Round (Gross) - No Wins"
	,"-- Lowest Round (Gross) - No DQs"
	,"-- Lowest Round (Gross) - No Wins, No DQs"
	,""
	,"Lowest Round (Net)"
	,"-- Lowest Round (Net) - No Wins"
	,"-- Lowest Round (Net) - No DQs"
	,"-- Lowest Round (Net) - No Wins, No DQs"
	,""
	,"Most Eagles"
	,"Most Birdies"
	,"Most Pars"
	,"Most Bogeys"
	,"Most Double Bogeys"
	,"Most Triple Bogeys"
	,"Most Worse Bogeys"
	,""
	,"Most Par or Better"

	]

}
