function html_GolferDetailStats(RoundsArray, Golfer, Event, Course, SeasonBegin, SeasonEnd) {
	/**---------------------------------------------------------------------**/
    	var pDataArray		=	arguments[0];
    	var pGolfer			=	arguments[1];
    	var pEvent			=	arguments[2];
    	var pCourse			=	arguments[3];
    	var pSeasonBegin	=	arguments[4];
    	var pSeasonEnd		=	arguments[5];
	/**---------------------------------------------------------------------**/

	document.write('<table border="0" width="270px" style="font-size: 0.95em;">');
	document.write('	<tr><td>&nbsp;</td></tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Events:</th>');
	document.write('		<td align="center" width="110px">' + getEventCount(pDataArray,pGolfer,pEvent,pCourse,pSeasonBegin,pSeasonEnd) + '</td>');
	document.write('	</tr>');
	document.write('	<tr><td>&nbsp;</td></tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Best Finish:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Worst Finish:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr><td>&nbsp;</td></tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">DQ\'s:</th>');
	document.write('		<td align="center" width="110px">' + getPlacementCount(pDataArray,pGolfer,pEvent,pCourse,pSeasonBegin,pSeasonEnd,0,0) + '</td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Wins:</th>');
	document.write('		<td align="center" width="110px">' + getPlacementCount(pDataArray,pGolfer,pEvent,pCourse,pSeasonBegin,pSeasonEnd,1,1) + '</td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Runner-Ups:</th>');
	document.write('		<td align="center" width="110px">' + getPlacementCount(pDataArray,pGolfer,pEvent,pCourse,pSeasonBegin,pSeasonEnd,2,2) + '</td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Top 3\'s:</th>');
	document.write('		<td align="center" width="110px">' + getPlacementCount(pDataArray,pGolfer,pEvent,pCourse,pSeasonBegin,pSeasonEnd,1,3) + '</td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Top 5\'s:</th>');
	document.write('		<td align="center" width="110px">' + getPlacementCount(pDataArray,pGolfer,pEvent,pCourse,pSeasonBegin,pSeasonEnd,1,5) + '</td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Top 10\'s:</th>');
	document.write('		<td align="center" width="110px">' + getPlacementCount(pDataArray,pGolfer,pEvent,pCourse,pSeasonBegin,pSeasonEnd,1,10) + '</td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Top 16\'s:</th>');
	document.write('		<td align="center" width="110px">' + getPlacementCount(pDataArray,pGolfer,pEvent,pCourse,pSeasonBegin,pSeasonEnd,1,16) + '</td>');
	document.write('	</tr>');
	document.write('	<tr><td>&nbsp;</td></tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Average:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Par 3 Average:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Par 4 Average:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Par 5 Average:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr><td>&nbsp;</td></tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Low Front 9:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">High Front 9:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Low Back 9:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">High Back 9:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Low Round:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">High Round:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr><td>&nbsp;</td></tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Eagles:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Birdies:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Pars:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Bogeys:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Double Bogeys:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Triple Bogeys:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Worse Bogeys:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr><td>&nbsp;</td></tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Eagles %:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Birdies %:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Pars %:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Bogeys %:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Double Bogeys %:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Triple Bogeys %:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('	<tr>');
	document.write('		<th align="right" width="160px">Worse Bogeys %:</th>');
	document.write('		<td align="center" width="110px"></td>');
	document.write('	</tr>');
	document.write('</table>');
}